version: '3.8'
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=pulsare_app
      - DB_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pulsare_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # Volumen persistente para PostgreSQL

volumes:
  pgdata: # Declaración del volumen persistente
